export const allBooks = [
    { title: "Hateship, Friendship, Courtship, Loveship, Marriage", recommender: "sam-altman" },
    { title: "Superintelligence", recommender: "elon-musk" },
    { title: "The Better Angels of Our Nature", recommender: "mark-zuckerberg" },
    { title: "The Moment of Lift", recommender: "bill-gates" },
    { title: "Autobiography of a Yogi", recommender: "steve-jobs" },
    { title: "Siddhartha", recommender: "naval-ravikant" },
    { title: "Blueprint", recommender: "nassim-nicholas-taleb" },
    { title: "The Startup Way", recommender: "paul-graham" },
    { title: "Zero to One", recommender: "peter-thiel" },
    { title: "What's Your Problem?", recommender: "adam-grant" },
    { title: "The Little Book of Common Sense Investing", recommender: "charlie-munger" },
    { title: "Hackers", recommender: "donald-knuth" },
    { title: "Who Is Michael Ovitz?", recommender: "gary-vaynerchuk" },
    { title: "The Innovator's Dilemma", recommender: "guy-kawasaki" },
    { title: "The Score Takes Care of Itself", recommender: "jack-dorsey" },
    { title: "The Age of Napoleon", recommender: "larry-ellison" },
    { title: "The Last Lion", recommender: "larry-ellison" },
    { title: "The War of Art", recommender: "lex-fridman" },
    { title: "C Programming Language", recommender: "linus-torvalds" },
    { title: "Just Kids", recommender: "malcolm-gladwell" },
    { title: "Thinking in Bets", recommender: "marc-andreessen" },
    { title: "The Hard Thing About Hard Things", recommender: "larry-page" },
    { title: "Energy", recommender: "mark-zuckerberg" },
    { title: "The Innovator's Dilemma", recommender: "mark-cuban" },
    { title: "Sapiens", recommender: "nir-eyal" },
    { title: "The Ride of a Lifetime", recommender: "patrick-bet-david" },
    { title: "Hooked", recommender: "ryan-hoover" },
    { title: "Mindset", recommender: "satya-nadella" },
    { title: "The Long Tail", recommender: "seth-godin" },
    { title: "Surely You're Joking, Mr. Feynman!", recommender: "sergey-brin" },
    { title: "The Prophet", recommender: "tim-ferriss" },
    { title: "Shoe Dog", recommender: "tim-cook" },
    { title: "Business Adventures", recommender: "warren-buffett" },


    { title: "Bad Blood", recommender: "bill-gates" },
    { title: "The Future of Capitalism", recommender: "bill-gates" },
    { title: "Enlightenment Now", recommender: "bill-gates" },
    { title: "Leonardo da Vinci", recommender: "bill-gates" },
    { title: "Blueprint", recommender: "bill-gates" },
    { title: "An American Marriage", recommender: "bill-gates" },
    { title: "Business Adventures", recommender: "bill-gates" },
    { title: "Why We Sleep", recommender: "bill-gates" },
    { title: "The Bully Pulpit", recommender: "bill-gates" },
    { title: "How Not to Be Wrong", recommender: "bill-gates" },
    { title: "Principles", recommender: "bill-gates" },
    { title: "Billion Dollar Whale", recommender: "bill-gates" },
    { title: "The Better Angels of Our Nature", recommender: "bill-gates" },
    { title: "Blitzscaling", recommender: "bill-gates" },
    { title: "Moonwalking with Einstein", recommender: "bill-gates" },
    { title: "How to Lie with Statistics", recommender: "bill-gates" },
    { title: "Mindset", recommender: "bill-gates" },
    { title: "Energy", recommender: "bill-gates" },
    { title: "The Rational Optimist", recommender: "bill-gates" },
    { title: "When Breath Becomes Air", recommender: "bill-gates" },
    { title: "How Asia Works", recommender: "bill-gates" },
    { title: "A Full Life", recommender: "bill-gates" },
    { title: "The Moon Is a Harsh Mistress", recommender: "bill-gates" },
    { title: "Hit Refresh", recommender: "bill-gates" },
    { title: "Getting Better", recommender: "bill-gates" },
    { title: "Evicted", recommender: "bill-gates" },
    { title: "Homo Deus", recommender: "bill-gates" },
    { title: "Life Is What You Make It", recommender: "bill-gates" },
    { title: "Tools and Weapons", recommender: "bill-gates" },
    { title: "The Gene", recommender: "bill-gates" },
    { title: "Shoe Dog", recommender: "bill-gates" },
    { title: "The Rise and Fall of American Growth", recommender: "bill-gates" },
    { title: "Life 3.0", recommender: "bill-gates" },
    { title: "Guns, Germs, and Steel", recommender: "bill-gates" },
    { title: "Born a Crime", recommender: "bill-gates" },
    { title: "21 Lessons for the 21st Century", recommender: "bill-gates" },
    { title: "What If?", recommender: "bill-gates" },
    { title: "The Box", recommender: "bill-gates" },
    { title: "On Immunity", recommender: "bill-gates" },
    { title: "Measure What Matters", recommender: "bill-gates" },
    { title: "Sapiens", recommender: "bill-gates" },
    { title: "Thing Explainer", recommender: "bill-gates" },
    { title: "Tap Dancing to Work", recommender: "bill-gates" },
    { title: "Stress Test", recommender: "bill-gates" },
    { title: "Becoming Steve Jobs", recommender: "bill-gates" },
    { title: "Checklist Manifesto", recommender: "bill-gates" },
    { title: "The Splendid and the Vile", recommender: "bill-gates" },
    { title: "The New Jim Crow", recommender: "bill-gates" },
    { title: "The Spy and the Traitor", recommender: "bill-gates" },
    { title: "Range", recommender: "bill-gates" },
    { title: "The Great Gatsby", recommender: "bill-gates" },
    { title: "The Ride of a Lifetime", recommender: "bill-gates" },
    { title: "The Code Breaker", recommender: "bill-gates" },
    { title: "Project Hail Mary", recommender: "bill-gates" },
    { title: "Elegant Defense, An", recommender: "bill-gates" },
    { title: "Think Like a Rocket Scientist", recommender: "adam-grant" },
    { title: "Weird", recommender: "adam-grant" },
    { title: "Together", recommender: "adam-grant" },
    { title: "Remote Work Revolution", recommender: "adam-grant" },
    { title: "Quiet", recommender: "adam-grant" },
    { title: "When", recommender: "adam-grant" },
    { title: "Unsafe Thinking", recommender: "adam-grant" },
    { title: "Drop the Ball", recommender: "adam-grant" },
    { title: "Irresistible", recommender: "adam-grant" },
    { title: "The Culture Code", recommender: "adam-grant" },
    { title: "A Second Chance", recommender: "adam-grant" },
    { title: "That's What She Said", recommender: "adam-grant" },
    { title: "Option B", recommender: "adam-grant" },
    { title: "Just the Funny Parts", recommender: "adam-grant" },
    { title: "Hit Makers", recommender: "adam-grant" },
    { title: "Behind the Cloud", recommender: "aaron-levie" },
    { title: "Blue Ocean Strategy", recommender: "aaron-levie" },
    { title: "Crossing the Chasm", recommender: "aaron-levie" },
    { title: "The Innovator's Dilemma", recommender: "aaron-levie" },
    { title: "Positioning", recommender: "aaron-levie" },
    { title: "Dealing with Darwin", recommender: "aaron-levie" },
    { title: "Montaigne", recommender: "alain-de-botton" },
    { title: "Extreme Ownership", recommender: "alexis-ohanian" },
    { title: "The Great CEO Within", recommender: "alexis-ohanian" },
    { title: "Shoe Dog", recommender: "alexis-ohanian" },
    { title: "Super Pumped", recommender: "alexis-ohanian" },
    { title: "Daemon", recommender: "alexis-ohanian" },
    { title: "Founders at Work", recommender: "alexis-ohanian" },
    { title: "Billion Dollar Whale", recommender: "alexis-ohanian" },
    { title: "Masters of Doom", recommender: "alexis-ohanian" },
    { title: "Influence", recommender: "alexis-ohanian" },
    { title: "Frenemies", recommender: "alexis-ohanian" },
    { title: "Indistractable", recommender: "alexis-ohanian" },
    { title: "Why We Sleep", recommender: "alexis-ohanian" },
    { title: "The Boy Who Harnessed the Wind", recommender: "alexis-ohanian" },
    { title: "Bad Blood", recommender: "alexis-ohanian" },
    { title: "The Hard Thing About Hard Things", recommender: "alexis-ohanian" },
    { title: "The Ride of a Lifetime", recommender: "alexis-ohanian" },
    { title: "Can't Hurt Me", recommender: "alexis-ohanian" },
    { title: "Winners Take All", recommender: "alexis-ohanian" },
    { title: "The Lean Startup", recommender: "andrew-ng" },
    { title: "The Hard Thing About Hard Things", recommender: "andrew-ng" },
    { title: "So Good They Can't Ignore You", recommender: "andrew-ng" },
    { title: "Talking to Humans", recommender: "andrew-ng" },
    { title: "Crossing the Chasm", recommender: "andrew-ng" },
    { title: "Rocket Surgery Made Easy", recommender: "andrew-ng" },
    { title: "Zero to One", recommender: "andrew-ng" },
    { title: "Brotopia", recommender: "arianna-huffington" },
    { title: "AI Superpowers", recommender: "arianna-huffington" },
    { title: "Originals", recommender: "arianna-huffington" },
    { title: "Principles", recommender: "arianna-huffington" },
    { title: "Give and Take", recommender: "arianna-huffington" },
    { title: "Tiny Habits", recommender: "arianna-huffington" },
    { title: "Meditations", recommender: "arianna-huffington" },
    { title: "The Start-up of You", recommender: "arianna-huffington" },
    { title: "Breath", recommender: "arianna-huffington" },
    { title: "Only the Paranoid Survive", recommender: "ben-horowitz" },
    { title: "Zero to One", recommender: "ben-horowitz" },
    { title: "The Lean Startup", recommender: "ben-horowitz" },
    { title: "Swimming Across", recommender: "ben-horowitz" },
    { title: "The Innovator's Dilemma", recommender: "ben-horowitz" },
    { title: "High Output Management", recommender: "ben-horowitz" },
    { title: "Skin in the Game", recommender: "ben-horowitz" },
    { title: "Who Is Michael Ovitz?", recommender: "ben-horowitz" },
    { title: "No Rules Rules", recommender: "ben-horowitz" },
    { title: "The Wright Brothers", recommender: "bob-iger" },
    { title: "Born to Run", recommender: "bob-iger" },
    { title: "Between the World and Me", recommender: "bob-iger" },
    { title: "The Last Lion", recommender: "bob-iger" },
    { title: "Surely You're Joking, Mr. Feynman!", recommender: "brian-armstrong" },
    { title: "Hackers & Painters", recommender: "brian-armstrong" },
    { title: "High Growth Handbook", recommender: "brian-armstrong" },
    { title: "The 15 Commitments of Conscious Leadership", recommender: "brian-armstrong" },
    { title: "The Inmates Are Running the Asylum", recommender: "brian-armstrong" },
    { title: "The Wright Brothers", recommender: "brian-armstrong" },
    { title: "How to Talk So Kids Will Listen & Listen So Kids Will Talk", recommender: "brian-armstrong" },
    { title: "Don't Make Me Think", recommender: "brian-armstrong" },
    { title: "The God Delusion", recommender: "brian-armstrong" },
    { title: "Good To Great", recommender: "brian-armstrong" },
    { title: "High Output Management", recommender: "brian-armstrong" },
    { title: "The Dip", recommender: "brian-armstrong" },
    { title: "The 22 Immutable Laws of Marketing", recommender: "brian-armstrong" },
    { title: "Ready Player One", recommender: "brian-armstrong" },
    { title: "Becoming Steve Jobs", recommender: "brian-armstrong" },
    { title: "The Sovereign Individual", recommender: "brian-armstrong" },
    { title: "Project Hail Mary", recommender: "brian-armstrong" },
    { title: "The Master Switch", recommender: "brian-armstrong" },
    { title: "Extreme Ownership", recommender: "casey-neistat" },
    { title: "The Second World War", recommender: "casey-neistat" },
    { title: "American Kingpin", recommender: "casey-neistat" },
    { title: "Hatching Twitter", recommender: "casey-neistat" },
    { title: "The Autobiography of Malcolm X", recommender: "casey-neistat" },
    { title: "The Spy and the Traitor", recommender: "casey-neistat" },
    { title: "Ready Player One", recommender: "casey-neistat" },
    { title: "Outliers", recommender: "charlie-munger" },
    { title: "Titan", recommender: "charlie-munger" },
    { title: "The Blind Watchmaker", recommender: "charlie-munger" },
    { title: "The Selfish Gene", recommender: "charlie-munger" },
    { title: "Only the Paranoid Survive", recommender: "charlie-munger" },
    { title: "Getting to Yes", recommender: "charlie-munger" },
    { title: "The Autobiography of Benjamin Franklin", recommender: "charlie-munger" },
    { title: "The Outsiders", recommender: "charlie-munger" },
    { title: "Guns, Germs, and Steel", recommender: "charlie-munger" },
    { title: "Genome", recommender: "charlie-munger" },
    { title: "Influence", recommender: "charlie-munger" },
    { title: "Moby Dick", recommender: "daniel-goleman" },
    { title: "One Hundred Years of Solitude", recommender: "daniel-goleman" },
    { title: "The Adventures of Huckleberry Finn", recommender: "daniel-pink" },
    { title: "Man's Search for Meaning", recommender: "daniel-pink" },
    { title: "Levels of the Game", recommender: "daniel-pink" },
    { title: "Give and Take", recommender: "daniel-pink" },
    { title: "The War of Art", recommender: "daniel-pink" },
    { title: "A Sense of Where You Are", recommender: "daniel-pink" },
    { title: "Bird by Bird", recommender: "daniel-pink" },
    { title: "Together", recommender: "daniel-pink" },
    { title: "Hit Makers", recommender: "daniel-pink" },
    { title: "Cumulus", recommender: "daniel-pink" },
    { title: "The 4-Hour Workweek", recommender: "daniel-pink" },
    { title: "The 7 Habits of Highly Effective People", recommender: "daniel-pink" },
    { title: "Born a Crime", recommender: "daniel-pink" },
    { title: "Animal Farm", recommender: "daniel-pink" },
    { title: "Scarcity", recommender: "daniel-pink" },
    { title: "How Not to Be Wrong", recommender: "daniel-pink" },
    { title: "The Great Gatsby", recommender: "daniel-pink" },
    { title: "Daily Rituals", recommender: "daniel-pink" },
    { title: "Influence", recommender: "daniel-pink" },
    { title: "Quiet", recommender: "daniel-pink" },
    { title: "Think Like a Rocket Scientist", recommender: "daniel-pink" },
    { title: "Weird", recommender: "daniel-pink" },
    { title: "Getting Things Done", recommender: "daniel-pink" },
    { title: "What Technology Wants", recommender: "derek-sivers" },
    { title: "Too Soon Old, Too Late Smart", recommender: "derek-sivers" },
    { title: "Turning Pro", recommender: "derek-sivers" },
    { title: "Do the Work", recommender: "derek-sivers" },
    { title: "How We Decide", recommender: "derek-sivers" },
    { title: "The Innovator's Solution", recommender: "derek-sivers" },
    { title: "The Lessons of History", recommender: "derek-sivers" },
    { title: "Drive", recommender: "derek-sivers" },
    { title: "Principles", recommender: "derek-sivers" },
    { title: "Grit", recommender: "derek-sivers" },
    { title: "The Inevitable", recommender: "derek-sivers" },
    { title: "Peak", recommender: "derek-sivers" },
    { title: "Deep Work", recommender: "derek-sivers" },
    { title: "How to Fail at Almost Everything and Still Win Big", recommender: "derek-sivers" },
    { title: "Hackers & Painters", recommender: "derek-sivers" },
    { title: "Pre-Suasion", recommender: "derek-sivers" },
    { title: "A Short History of Nearly Everything", recommender: "derek-sivers" },
    { title: "The Bed of Procrustes", recommender: "derek-sivers" },
    { title: "The Pragmatic Programmer", recommender: "derek-sivers" },
    { title: "Meditations", recommender: "derek-sivers" },
    { title: "Give and Take", recommender: "derek-sivers" },
    { title: "How to Live", recommender: "derek-sivers" },
    { title: "Making Ideas Happen", recommender: "derek-sivers" },
    { title: "Homo Deus", recommender: "derek-sivers" },
    { title: "The Lean Startup", recommender: "derek-sivers" },
    { title: "The Culture Code", recommender: "derek-sivers" },
    { title: "Here Comes Everybody", recommender: "derek-sivers" },
    { title: "Seeking Wisdom", recommender: "derek-sivers" },
    { title: "The E-Myth Revisited", recommender: "derek-sivers" },
    { title: "Atomic Habits", recommender: "derek-sivers" },
    { title: "Antifragile", recommender: "derek-sivers" },
    { title: "Sum", recommender: "derek-sivers" },
    { title: "On Writing Well", recommender: "derek-sivers" },
    { title: "Life 3.0", recommender: "derek-sivers" },
    { title: "Au Contraire", recommender: "derek-sivers" },
    { title: "The Truth", recommender: "derek-sivers" },
    { title: "Switch", recommender: "derek-sivers" },
    { title: "Thinking in Bets", recommender: "derek-sivers" },
    { title: "The Courage to Be Disliked", recommender: "derek-sivers" },
    { title: "Zero to One", recommender: "derek-sivers" },
    { title: "The Willpower Instinct", recommender: "derek-sivers" },
    { title: "The Happiness Hypothesis", recommender: "derek-sivers" },
    { title: "Predictably Irrational", recommender: "derek-sivers" },
    { title: "The Ultimate Sales Machine", recommender: "derek-sivers" },
    { title: "The Smartest Investment Book You'll Ever Read", recommender: "derek-sivers" },
    { title: "The Wisdom of Crowds", recommender: "derek-sivers" },
    { title: "Stubborn Attachments", recommender: "derek-sivers" },
    { title: "The Dip", recommender: "derek-sivers" },
    { title: "Smartcuts", recommender: "derek-sivers" },
    { title: "The Obstacle Is the Way", recommender: "derek-sivers" },
    { title: "Mastery", recommender: "derek-sivers" },
    { title: "Willpower", recommender: "derek-sivers" },
    { title: "The Power of Full Engagement", recommender: "derek-sivers" },
    { title: "Mindset", recommender: "derek-sivers" },
    { title: "So Good They Can't Ignore You", recommender: "derek-sivers" },
    { title: "Sapiens", recommender: "derek-sivers" },
    { title: "Made to Stick", recommender: "derek-sivers" },
    { title: "The Talent Code", recommender: "derek-sivers" },
    { title: "Influence", recommender: "derek-sivers" },
    { title: "The Magic of Thinking Big", recommender: "derek-sivers" },
    { title: "The Paradox of Choice", recommender: "derek-sivers" },
    { title: "Guns, Germs, and Steel", recommender: "derek-sivers" },
    { title: "The War of Art", recommender: "derek-sivers" },
    { title: "A Geek in Japan", recommender: "derek-sivers" },
    { title: "How to Talk So Kids Will Listen & Listen So Kids Will Talk", recommender: "derek-sivers" },
    { title: "Thinking, Fast and Slow", recommender: "derek-sivers" },
    { title: "The 4-Hour Workweek", recommender: "derek-sivers" },
    { title: "Man's Search for Meaning", recommender: "derek-sivers" },
    { title: "The Power of Habit", recommender: "derek-sivers" },
    { title: "The Subtle Art of Not Giving a F*ck", recommender: "derek-sivers" },
    { title: "12 Rules for Life", recommender: "derek-sivers" },
    { title: "Quiet", recommender: "derek-sivers" },
    { title: "The 48 Laws of Power", recommender: "derek-sivers" },
    { title: "The Entrepreneur Roller Coaster", recommender: "derek-sivers" },
    { title: "Getting Things Done", recommender: "derek-sivers" },
    { title: "Emergency", recommender: "derek-sivers" },
    { title: "Poor Charlie's Almanack", recommender: "derek-sivers" },
    { title: "On Writing", recommender: "derek-sivers" },
    { title: "When", recommender: "derek-sivers" },
    { title: "Moonwalking with Einstein", recommender: "derek-sivers" },
    { title: "A Guide to the Good Life", recommender: "derek-sivers" },
    { title: "How to Win Friends and Influence People", recommender: "derek-sivers" },
    { title: "Mountains Beyond Mountains", recommender: "donald-knuth" },
    { title: "Getting to Yes", recommender: "drew-houston" },
    { title: "The Hard Thing About Hard Things", recommender: "drew-houston" },
    { title: "Principles", recommender: "drew-houston" },
    { title: "Zen and the Art of Motorcycle Maintenance", recommender: "drew-houston" },
    { title: "Poor Charlie's Almanack", recommender: "drew-houston" },
    { title: "Crossing the Chasm", recommender: "drew-houston" },
    { title: "High Output Management", recommender: "drew-houston" },
    { title: "The Effective Executive", recommender: "drew-houston" },
    { title: "Seeking Wisdom", recommender: "drew-houston" },
    { title: "The Innovator's Dilemma", recommender: "drew-houston" },
    { title: "Man's Search for Meaning", recommender: "dustin-moskowitz" },
    { title: "Measure What Matters", recommender: "dustin-moskowitz" },
    { title: "Getting to Yes", recommender: "dustin-moskowitz" },
    { title: "Getting Things Done", recommender: "dustin-moskowitz" },
    { title: "The Hard Thing About Hard Things", recommender: "dustin-moskowitz" },
    { title: "The 15 Commitments of Conscious Leadership", recommender: "dustin-moskowitz" },
    { title: "Nonviolent Communication", recommender: "dustin-moskowitz" },
    { title: "Zero to One", recommender: "dustin-moskowitz" },
    { title: "The Lean Startup", recommender: "dustin-moskowitz" },
    { title: "Secrets of Sand Hill Road", recommender: "elad-gil" },
    { title: "Life 3.0", recommender: "elon-musk" },
    { title: "If the Universe Is Teeming with Aliens ... WHERE IS EVERYBODY?", recommender: "elon-musk" },
    { title: "Benjamin Franklin", recommender: "elon-musk" },
    { title: "Daemon", recommender: "elon-musk" },
    { title: "Steve Jobs", recommender: "elon-musk" },
    { title: "Zero to One", recommender: "elon-musk" },
    { title: "The Player of Games", recommender: "elon-musk" },
    { title: "Human Compatible", recommender: "elon-musk" },
    { title: "The Hitchhiker's Guide to the Galaxy", recommender: "elon-musk" },
    { title: "Lying", recommender: "elon-musk" },
    { title: "The Age of Napoleon", recommender: "elon-musk" },
    { title: "The Lord of the Rings", recommender: "elon-musk" },
    { title: "Dune", recommender: "elon-musk" },
    { title: "Foundation", recommender: "elon-musk" },
    { title: "The Wealth Of Nations", recommender: "elon-musk" },
    { title: "Zero to One", recommender: "eric-weinstein" },
    { title: "The Martian", recommender: "ev-williams" },
    { title: "Hackers & Painters", recommender: "ev-williams" },
    { title: "Mindset", recommender: "ev-williams" },
    { title: "The Halo Effect", recommender: "ev-williams" },
    { title: "Antifragile", recommender: "ev-williams" },
    { title: "Cumulus", recommender: "ev-williams" },
    { title: "Good To Great", recommender: "ev-williams" },
    { title: "The Innovator's Dilemma", recommender: "ev-williams" },
    { title: "The Effective Executive", recommender: "ev-williams" },
    { title: "The Dip", recommender: "ev-williams" },
    { title: "Jonathan Livingston Seagull", recommender: "ev-williams" },
    { title: "Zen and the Art of Motorcycle Maintenance", recommender: "ev-williams" },
    { title: "Thinking, Fast and Slow", recommender: "ev-williams" },
    { title: "Getting Things Done", recommender: "ev-williams" },
    { title: "The Dhammapada", recommender: "gabor-mate" },
    { title: "Mr. Putin", recommender: "garry-kasparov" },
    { title: "A Very Expensive Poison", recommender: "garry-kasparov" },
    { title: "Red Notice", recommender: "garry-kasparov" },
    { title: "Influence", recommender: "guy-kawasaki" },
    { title: "The Effective Executive", recommender: "guy-kawasaki" },
    { title: "The Four Steps to the Epiphany", recommender: "guy-kawasaki" },
    { title: "How to Change", recommender: "guy-kawasaki" },
    { title: "The Master and Margarita", recommender: "jack-dorsey" },
    { title: "Principles", recommender: "jack-dorsey" },
    { title: "Becoming Steve Jobs", recommender: "jack-dorsey" },
    { title: "The Four Agreements", recommender: "jack-dorsey" },
    { title: "Checklist Manifesto", recommender: "jack-dorsey" },
    { title: "Between the World and Me", recommender: "jack-dorsey" },
    { title: "Whole Earth Discipline", recommender: "jack-dorsey" },
    { title: "The Mythical Man-Month", recommender: "jeff-atwood" },
    { title: "Peopleware", recommender: "jeff-atwood" },
    { title: "The Inmates Are Running the Asylum", recommender: "jeff-atwood" },
    { title: "About Face", recommender: "jeff-atwood" },
    { title: "Don't Make Me Think", recommender: "jeff-atwood" },
    { title: "The Visual Display of Quantitative Information", recommender: "jeff-atwood" },
    { title: "The Pragmatic Programmer", recommender: "jeff-atwood" },
    { title: "The Innovator's Solution", recommender: "jeff-bezos" },
    { title: "The Effective Executive", recommender: "jeff-bezos" },
    { title: "Sam Walton", recommender: "jeff-bezos" },
    { title: "The Mythical Man-Month", recommender: "jeff-bezos" },
    { title: "The Black Swan", recommender: "jeff-bezos" },
    { title: "Built to Last", recommender: "jeff-bezos" },
    { title: "The Innovator's Dilemma", recommender: "jeff-bezos" },
    { title: "Rework", recommender: "jeff-bezos" },
    { title: "Dune", recommender: "jeff-bezos" },
    { title: "The Fountainhead", recommender: "jimmy-wales" },
    { title: "The Martian", recommender: "jimmy-wales" },
    { title: "Blood Meridian", recommender: "jocko-willink" },
    { title: "About Face", recommender: "jocko-willink" },
    { title: "Animal Farm", recommender: "jocko-willink" },
    { title: "The War of Art", recommender: "joe-rogan" },
    { title: "Can't Hurt Me", recommender: "joe-rogan" },
    { title: "Outliers", recommender: "joe-rogan" },
    { title: "Sapiens", recommender: "joe-rogan" },
    { title: "The Talent Code", recommender: "joe-rogan" },
    { title: "The God Delusion", recommender: "joe-rogan" },
    { title: "21 Lessons for the 21st Century", recommender: "joe-rogan" },
    { title: "Guns, Germs, and Steel", recommender: "joe-rogan" },
    { title: "Tribe", recommender: "joe-rogan" },
    { title: "Empire of the Summer Moon", recommender: "joe-rogan" },
    { title: "The Happiness Hypothesis", recommender: "joe-rogan" },
    { title: "The Tipping Point", recommender: "joe-rogan" },
    { title: "The Four Agreements", recommender: "joe-rogan" },
    { title: "The Book of Five Rings", recommender: "joe-rogan" },
    { title: "Breath", recommender: "joe-rogan" },
    { title: "Turning Pro", recommender: "joe-rogan" },
    { title: "Without You, There Is No Us", recommender: "jon-stewart" },
    { title: "Grit", recommender: "joshua-waitzkin" },
    { title: "Zen and the Art of Motorcycle Maintenance", recommender: "joshua-waitzkin" },
    { title: "Tao Te Ching", recommender: "joshua-waitzkin" },
    { title: "On the Road", recommender: "joshua-waitzkin" },
    { title: "Shantaram", recommender: "joshua-waitzkin" },
    { title: "The Mythical Man-Month", recommender: "larry-ellison" },
    { title: "High Output Management", recommender: "larry-ellison" },
    { title: "The Fountainhead", recommender: "larry-ellison" },
    { title: "Measure What Matters", recommender: "larry-page" },
    { title: "The Better Angels of Our Nature", recommender: "lex-fridman" },
    { title: "Life 3.0", recommender: "lex-fridman" },
    { title: "Empire of the Summer Moon", recommender: "lex-fridman" },
    { title: "Sapiens", recommender: "lex-fridman" },
    { title: "A New Kind of Science", recommender: "lex-fridman" },
    { title: "Irresistible", recommender: "malcolm-gladwell" },
    { title: "Drunk Tank Pink", recommender: "malcolm-gladwell" },
    { title: "The Big Short", recommender: "malcolm-gladwell" },
    { title: "Together", recommender: "malcolm-gladwell" },
    { title: "Checklist Manifesto", recommender: "malcolm-gladwell" },
    { title: "Think Again", recommender: "malcolm-gladwell" },
    { title: "Extreme Ownership", recommender: "marc-andreessen" },
    { title: "The Rational Optimist", recommender: "marc-andreessen" },
    { title: "Can't Hurt Me", recommender: "marc-andreessen" },
    { title: "The Courage to Be Disliked", recommender: "marc-andreessen" },
    { title: "Born Standing Up", recommender: "marc-andreessen" },
    { title: "Behave", recommender: "marc-andreessen" },
    { title: "Edison", recommender: "marc-andreessen" },
    { title: "Zero to One", recommender: "marc-andreessen" },
    { title: "Whole Earth Discipline", recommender: "marc-andreessen" },
    { title: "Who Is Michael Ovitz?", recommender: "marc-andreessen" },
    { title: "Poor Charlie's Almanack", recommender: "marc-andreessen" },
    { title: "Becoming Steve Jobs", recommender: "marc-andreessen" },
    { title: "Only the Paranoid Survive", recommender: "marc-andreessen" },
    { title: "High Output Management", recommender: "marc-andreessen" },
    { title: "Expert Political Judgment", recommender: "marc-andreessen" },
    { title: "How to Live", recommender: "marc-andreessen" },
    { title: "Skin in the Game", recommender: "marc-andreessen" },
    { title: "The Lean Startup", recommender: "marc-andreessen" },
    { title: "The Hard Thing About Hard Things", recommender: "marc-andreessen" },
    { title: "The Myth of the Rational Voter", recommender: "marc-andreessen" },
    { title: "A Guide to the Good Life", recommender: "marc-andreessen" },
    { title: "Thinking, Fast and Slow", recommender: "marc-andreessen" },
    { title: "12 Rules for Life", recommender: "marc-andreessen" },
    { title: "The Ancient City", recommender: "marc-andreessen" },
    { title: "Who We Are and How We Got Here", recommender: "marc-andreessen" },
    { title: "The True Believer", recommender: "marc-andreessen" },
    { title: "The Righteous Mind", recommender: "marc-andreessen" },
    { title: "A Very Expensive Poison", recommender: "marc-andreessen" },
    { title: "Principles", recommender: "marc-benioff" },
    { title: "The Mythical Man-Month", recommender: "marc-benioff" },
    { title: "Autobiography of a Yogi", recommender: "marc-benioff" },
    { title: "The Art of War", recommender: "marc-benioff" },
    { title: "Principles", recommender: "mark-cuban" },
    { title: "Rework", recommender: "mark-cuban" },
    { title: "That's What She Said", recommender: "mark-cuban" },
    { title: "The Fountainhead", recommender: "mark-cuban" },
    { title: "The Master Algorithm", recommender: "mark-cuban" },
    { title: "The Sports Gene", recommender: "mark-cuban" },
    { title: "Mr. Putin", recommender: "mark-cuban" },
    { title: "On Immunity", recommender: "mark-zuckerberg" },
    { title: "Creativity, Inc.", recommender: "mark-zuckerberg" },
    { title: "The Player of Games", recommender: "mark-zuckerberg" },
    { title: "Why Nations Fail", recommender: "mark-zuckerberg" },
    { title: "The Idea Factory", recommender: "mark-zuckerberg" },
    { title: "The Structure of Scientific Revolutions", recommender: "mark-zuckerberg" },
    { title: "The Rational Optimist", recommender: "mark-zuckerberg" },
    { title: "Sapiens", recommender: "mark-zuckerberg" },
    { title: "The Three-Body Problem", recommender: "mark-zuckerberg" },
    { title: "The New Jim Crow", recommender: "mark-zuckerberg" },
    { title: "Genome", recommender: "mark-zuckerberg" },
    { title: "The Aeneid", recommender: "mark-zuckerberg" },
    { title: "The Beginning of Infinity", recommender: "mark-zuckerberg" },
    { title: "The Hard Thing About Hard Things", recommender: "mark-zuckerberg" },
    { title: "Zero to One", recommender: "mark-zuckerberg" },
    { title: "High Output Management", recommender: "mark-zuckerberg" },
    { title: "Ender's Game", recommender: "mark-zuckerberg" },
    { title: "Structure and Interpretation of Computer Programs", recommender: "max-levchin" },
    { title: "The Master and Margarita", recommender: "max-levchin" },
    { title: "Predictably Irrational", recommender: "max-levchin" },
    { title: "The Hard Thing About Hard Things", recommender: "max-levchin" },
    { title: "Zero to One", recommender: "max-levchin" },
    { title: "Thinking in Bets", recommender: "max-levchin" },
    { title: "Influence", recommender: "max-levchin" },
    { title: "The Innovator's Dilemma", recommender: "max-levchin" },
    { title: "The Coddling of the American Mind", recommender: "max-levchin" },
    { title: "High Growth Handbook", recommender: "max-levchin" },
    { title: "The Power of Habit", recommender: "max-levchin" },
    { title: "Good To Great", recommender: "max-levchin" },
    { title: "The Complete Stories", recommender: "max-levchin" },
    { title: "Enlightenment Now", recommender: "melinda-gates" },
    { title: "Sapiens", recommender: "melinda-gates" },
    { title: "Talking to Strangers", recommender: "melinda-gates" },
    { title: "Think Again", recommender: "melinda-gates" },
    { title: "Principles", recommender: "michael-bloomberg" },
    { title: "The Innovator's Dilemma", recommender: "michael-bloomberg" },
    { title: "The Start-up of You", recommender: "michael-bloomberg" },
    { title: "Business Adventures", recommender: "michael-dell" },
    { title: "The Outsiders", recommender: "michael-dell" },
    { title: "Abundance", recommender: "michael-dell" },
    { title: "The Second Machine Age", recommender: "michael-dell" },
    { title: "The Hard Thing About Hard Things", recommender: "michael-dell" },
    { title: "Who We Are and How We Got Here", recommender: "nassim-nicholas-taleb" },
    { title: "A New Kind of Science", recommender: "nassim-nicholas-taleb" },
    { title: "Exhalation", recommender: "naval-ravikant" },
    { title: "The Evolution of Everything", recommender: "naval-ravikant" },
    { title: "Fooled by Randomness", recommender: "naval-ravikant" },
    { title: "Genome", recommender: "naval-ravikant" },
    { title: "The Lessons of History", recommender: "naval-ravikant" },
    { title: "The Diamond Age", recommender: "naval-ravikant" },
    { title: "The Bed of Procrustes", recommender: "naval-ravikant" },
    { title: "Poor Charlie's Almanack", recommender: "naval-ravikant" },
    { title: "The Complete Stories", recommender: "naval-ravikant" },
    { title: "Pre-Suasion", recommender: "naval-ravikant" },
    { title: "The Beginning of Infinity", recommender: "naval-ravikant" },
    { title: "Thing Explainer", recommender: "naval-ravikant" },
    { title: "Antifragile", recommender: "naval-ravikant" },
    { title: "The Black Swan", recommender: "naval-ravikant" },
    { title: "The Sovereign Individual", recommender: "naval-ravikant" },
    { title: "Skin in the Game", recommender: "naval-ravikant" },
    { title: "How to Change Your Mind", recommender: "naval-ravikant" },
    { title: "Meditations", recommender: "naval-ravikant" },
    { title: "A Pattern Language", recommender: "naval-ravikant" },
    { title: "The Red Queen", recommender: "naval-ravikant" },
    { title: "Homo Deus", recommender: "naval-ravikant" },
    { title: "Letters from a Stoic", recommender: "naval-ravikant" },
    { title: "Too Soon Old, Too Late Smart", recommender: "naval-ravikant" },
    { title: "Permutation City", recommender: "naval-ravikant" },
    { title: "Spiritual Enlightenment, the Damnedest Thing", recommender: "naval-ravikant" },
    { title: "The Three-Body Problem", recommender: "naval-ravikant" },
    { title: "G\xf6del, Escher, Bach", recommender: "naval-ravikant" },
    { title: "Awareness", recommender: "naval-ravikant" },
    { title: "The Rational Optimist", recommender: "naval-ravikant" },
    { title: "Influence", recommender: "naval-ravikant" },
    { title: "Surely You're Joking, Mr. Feynman!", recommender: "naval-ravikant" },
    { title: "The Hitchhiker's Guide to the Galaxy", recommender: "naval-ravikant" },
    { title: "Economics in One Lesson", recommender: "naval-ravikant" },
    { title: "Good Calories, Bad Calories", recommender: "naval-ravikant" },
    { title: "The Wealth Of Nations", recommender: "naval-ravikant" },
    { title: "Sapiens", recommender: "naval-ravikant" },
    { title: "The Power of Now", recommender: "naval-ravikant" },
    { title: "The Power of Habit", recommender: "naval-ravikant" },
    { title: "The Lord of the Rings", recommender: "naval-ravikant" },
    { title: "The Untethered Soul", recommender: "naval-ravikant" },
    { title: "The Prophet", recommender: "naval-ravikant" },
    { title: "Snow Crash", recommender: "naval-ravikant" },
    { title: "Foundation", recommender: "naval-ravikant" },
    { title: "Stories of Your Life and Others", recommender: "naval-ravikant" },
    { title: "Fahrenheit 451", recommender: "nir-eyal" },
    { title: "The Sun Does Shine", recommender: "oprah-winfrey" },
    { title: "An American Marriage", recommender: "oprah-winfrey" },
    { title: "The Power of Now", recommender: "oprah-winfrey" },
    { title: "The Untethered Soul", recommender: "oprah-winfrey" },
    { title: "Trillion Dollar Coach", recommender: "patrick-bet-david" },
    { title: "Measure What Matters", recommender: "patrick-bet-david" },
    { title: "The Founders", recommender: "patrick-bet-david" },
    { title: "Meditations", recommender: "patrick-bet-david" },
    { title: "Talking to Strangers", recommender: "patrick-bet-david" },
    { title: "Range", recommender: "patrick-bet-david" },
    { title: "The Idea Factory", recommender: "patrick-collison" },
    { title: "Masters of Doom", recommender: "patrick-collison" },
    { title: "Dealers of Lightning", recommender: "patrick-collison" },
    { title: "Season of the Witch", recommender: "patrick-collison" },
    { title: "The Beginning of Infinity", recommender: "patrick-collison" },
    { title: "A Pattern Language", recommender: "patrick-collison" },
    { title: "Swimming Across", recommender: "patrick-collison" },
    { title: "If the Universe Is Teeming with Aliens ... WHERE IS EVERYBODY?", recommender: "patrick-collison" },
    { title: "The Rise and Fall of American Growth", recommender: "patrick-collison" },
    { title: "Poor Charlie's Almanack", recommender: "patrick-collison" },
    { title: "C Programming Language", recommender: "patrick-collison" },
    { title: "Structure and Interpretation of Computer Programs", recommender: "patrick-collison" },
    { title: "Tuxedo Park", recommender: "patrick-collison" },
    { title: "How Asia Works", recommender: "patrick-collison" },
    { title: "Leadership", recommender: "patrick-collison" },
    { title: "The Moon Is a Harsh Mistress", recommender: "paul-graham" },
    { title: "How to Win Friends and Influence People", recommender: "paul-graham" },
    { title: "Benjamin Franklin", recommender: "paul-graham" },
    { title: "Lives of the Artists", recommender: "paul-graham" },
    { title: "The Ancient City", recommender: "paul-graham" },
    { title: "Medieval Technology and Social Change", recommender: "paul-graham" },
    { title: "Structure and Interpretation of Computer Programs", recommender: "paul-graham" },
    { title: "The Old Way", recommender: "paul-graham" },
    { title: "The Hobbit", recommender: "paul-graham" },
    { title: "Founders at Work", recommender: "paul-graham" },
    { title: "Barbarian Days", recommender: "paul-graham" },
    { title: "A Sense of Where You Are", recommender: "paul-graham" },
    { title: "Hard Drive", recommender: "paul-graham" },
    { title: "The Mythical Man-Month", recommender: "paul-graham" },
    { title: "The Lord of the Rings", recommender: "paul-graham" },
    { title: "The Autobiography of Benjamin Franklin", recommender: "paul-graham" },
    { title: "More Money Than God", recommender: "paul-graham" },
    { title: "Foundation", recommender: "paul-graham" },
    { title: "The Master and Margarita", recommender: "peter-thiel" },
    { title: "The Diamond Age", recommender: "peter-thiel" },
    { title: "The Hard Thing About Hard Things", recommender: "peter-thiel" },
    { title: "Originals", recommender: "peter-thiel" },
    { title: "Atlas Shrugged", recommender: "peter-thiel" },
    { title: "The Lord of the Rings", recommender: "peter-thiel" },
    { title: "Principles", recommender: "reed-hastings" },
    { title: "Tools and Weapons", recommender: "reed-hastings" },
    { title: "Conscious Business", recommender: "reid-hoffman" },
    { title: "Tools and Weapons", recommender: "reid-hoffman" },
    { title: "Sapiens", recommender: "reid-hoffman" },
    { title: "High Growth Handbook", recommender: "reid-hoffman" },
    { title: "Measure What Matters", recommender: "reid-hoffman" },
    { title: "The Moment of Lift", recommender: "reid-hoffman" },
    { title: "The Lord of the Rings", recommender: "reid-hoffman" },
    { title: "The Hobbit", recommender: "richard-branson" },
    { title: "Travels with Charley in Search of America", recommender: "richard-branson" },
    { title: "A Full Life", recommender: "richard-branson" },
    { title: "1984", recommender: "richard-branson" },
    { title: "Happiness", recommender: "richard-branson" },
    { title: "The Right Stuff", recommender: "richard-branson" },
    { title: "The Hitchhiker's Guide to the Galaxy", recommender: "richard-branson" },
    { title: "Originals", recommender: "richard-branson" },
    { title: "Remote", recommender: "richard-branson" },
    { title: "Lean In", recommender: "richard-branson" },
    { title: "Where the Wild Things Are", recommender: "richard-branson" },
    { title: "Abundance", recommender: "richard-branson" },
    { title: "Homo Deus", recommender: "richard-branson" },
    { title: "Mountains Beyond Mountains", recommender: "richard-branson" },
    { title: "Just Mercy", recommender: "richard-branson" },
    { title: "Sapiens", recommender: "richard-branson" },
    { title: "The Adventures of Huckleberry Finn", recommender: "richard-branson" },
    { title: "One Hundred Years of Solitude", recommender: "richard-branson" },
    { title: "Shantaram", recommender: "richard-branson" },
    { title: "The Sun Does Shine", recommender: "richard-branson" },
    { title: "Barbarian Days", recommender: "richard-branson" },
    { title: "The Landmark Thucydides", recommender: "robert-greene" },
    { title: "The Prince", recommender: "robert-greene" },
    { title: "Taking the Work Out of Networking", recommender: "ryan-hoover" },
    { title: "The Courage to Be Disliked", recommender: "ryan-hoover" },
    { title: "The Great CEO Within", recommender: "ryan-hoover" },
    { title: "The Four Steps to the Epiphany", recommender: "ryan-hoover" },
    { title: "The Art of Game Design", recommender: "ryan-hoover" },
    { title: "Indistractable", recommender: "ryan-hoover" },
    { title: "Crush It!", recommender: "ryan-hoover" },
    { title: "The Untethered Soul", recommender: "ryan-hoover" },
    { title: "Lives of the Artists", recommender: "ryan-holiday" },
    { title: "The War of Art", recommender: "ryan-holiday" },
    { title: "The 48 Laws of Power", recommender: "ryan-holiday" },
    { title: "The River of Doubt", recommender: "ryan-holiday" },
    { title: "Bird by Bird", recommender: "ryan-holiday" },
    { title: "The Score Takes Care of Itself", recommender: "ryan-holiday" },
    { title: "Founders at Work", recommender: "ryan-holiday" },
    { title: "Titan", recommender: "ryan-holiday" },
    { title: "Endurance", recommender: "ryan-holiday" },
    { title: "Letters from a Stoic", recommender: "ryan-holiday" },
    { title: "The Aeneid", recommender: "ryan-holiday" },
    { title: "The Moral Animal", recommender: "ryan-holiday" },
    { title: "The Autobiography of Malcolm X", recommender: "ryan-holiday" },
    { title: "The Fish That Ate the Whale", recommender: "ryan-holiday" },
    { title: "How to Live", recommender: "ryan-holiday" },
    { title: "Man's Search for Meaning", recommender: "ryan-holiday" },
    { title: "Mastery", recommender: "ryan-holiday" },
    { title: "Leadership", recommender: "ryan-holiday" },
    { title: "The Prince", recommender: "ryan-holiday" },
    { title: "The Great Gatsby", recommender: "ryan-holiday" },
    { title: "Range", recommender: "ryan-holiday" },
    { title: "Meditations", recommender: "ryan-holiday" },
    { title: "Blood Meridian", recommender: "ryan-holiday" },
    { title: "Blue Ocean Strategy", recommender: "ryan-holiday" },
    { title: "Essentialism", recommender: "ryan-holiday" },
    { title: "Ender's Game", recommender: "ryan-holiday" },
    { title: "The 4-Hour Workweek", recommender: "ryan-holiday" },
    { title: "Montaigne", recommender: "ryan-holiday" },
    { title: "The Black Swan", recommender: "ryan-holiday" },
    { title: "The Truth", recommender: "ryan-holiday" },
    { title: "The Landmark Thucydides", recommender: "ryan-holiday" },
    { title: "The Book of Five Rings", recommender: "ryan-holiday" },
    { title: "Zero to One", recommender: "rupert-murdoch" },
    { title: "The Rational Optimist", recommender: "rupert-murdoch" },
    { title: "The Three-Body Problem", recommender: "sahil-bloom" },
    { title: "The Success Equation", recommender: "sahil-bloom" },
    { title: "Benjamin Franklin", recommender: "sahil-bloom" },
    { title: "Leonardo da Vinci", recommender: "sahil-bloom" },
    { title: "The River of Doubt", recommender: "sahil-bloom" },
    { title: "The Splendid and the Vile", recommender: "sahil-bloom" },
    { title: "When Breath Becomes Air", recommender: "sahil-bloom" },
    { title: "The Fish That Ate the Whale", recommender: "sahil-bloom" },
    { title: "Thinking, Fast and Slow", recommender: "sahil-bloom" },
    { title: "The 4-Hour Workweek", recommender: "sahil-bloom" },
    { title: "Atomic Habits", recommender: "sahil-bloom" },
    { title: "1984", recommender: "sahil-bloom" },
    { title: "Barbarian Days", recommender: "sahil-bloom" },
    { title: "What's Our Problem?", recommender: "sahil-bloom" },
    { title: "Autobiography of a Yogi", recommender: "sahil-lavingia" },
    { title: "Moonwalking with Einstein", recommender: "sahil-lavingia" },
    { title: "Foundation", recommender: "sahil-lavingia" },
    { title: "Surely You're Joking, Mr. Feynman!", recommender: "sahil-lavingia" },
    { title: "Born Standing Up", recommender: "sahil-lavingia" },
    { title: "Tribal Leadership", recommender: "sahil-lavingia" },
    { title: "Anything You Want", recommender: "sahil-lavingia" },
    { title: "The Sovereign Individual", recommender: "sahil-lavingia" },
    { title: "G\xf6del, Escher, Bach", recommender: "sahil-lavingia" },
    { title: "Born to Run", recommender: "sahil-lavingia" },
    { title: "Brave New World", recommender: "sahil-lavingia" },
    { title: "The Hitchhiker's Guide to the Galaxy", recommender: "sahil-lavingia" },
    { title: "Dune", recommender: "sahil-lavingia" },
    { title: "Made to Stick", recommender: "sahil-lavingia" },
    { title: "High Output Management", recommender: "sahil-lavingia" },
    { title: "Stranger in a Strange Land", recommender: "sahil-lavingia" },
    { title: "Animal Farm", recommender: "sahil-lavingia" },
    { title: "Thinking, Fast and Slow", recommender: "sahil-lavingia" },
    { title: "How to Win Friends and Influence People", recommender: "sahil-lavingia" },
    { title: "Skin in the Game", recommender: "sahil-lavingia" },
    { title: "Sapiens", recommender: "sahil-lavingia" },
    { title: "The New Jim Crow", recommender: "sahil-lavingia" },
    { title: "Nonviolent Communication", recommender: "satya-nadella" },
    { title: "The Rise and Fall of American Growth", recommender: "satya-nadella" },
    { title: "Influence", recommender: "scott-adams" },
    { title: "Pre-Suasion", recommender: "scott-adams" },
    { title: "Thinking, Fast and Slow", recommender: "scott-adams" },
    { title: "How to Win Friends and Influence People", recommender: "scott-adams" },
    { title: "Steve Jobs", recommender: "scott-adams" },
    { title: "The Power of Habit", recommender: "scott-adams" },
    { title: "How to Fail at Almost Everything and Still Win Big", recommender: "scott-adams" },
    { title: "Snow Crash", recommender: "sergey-brin" },
    { title: "Makers", recommender: "seth-godin" },
    { title: "Give and Take", recommender: "seth-godin" },
    { title: "Originals", recommender: "seth-godin" },
    { title: "Crossing the Chasm", recommender: "seth-godin" },
    { title: "Understanding Comics", recommender: "seth-godin" },
    { title: "Rework", recommender: "seth-godin" },
    { title: "Just Kids", recommender: "seth-godin" },
    { title: "Thirst", recommender: "seth-godin" },
    { title: "A Second Chance", recommender: "seth-godin" },
    { title: "The Diamond Age", recommender: "seth-godin" },
    { title: "Dune", recommender: "seth-godin" },
    { title: "Snow Crash", recommender: "seth-godin" },
    { title: "Thinking in Bets", recommender: "seth-godin" },
    { title: "Blitzscaling", recommender: "sam-altman" },
    { title: "Superintelligence", recommender: "sam-altman" },
    { title: "Meditations", recommender: "sam-altman" },
    { title: "Medieval Technology and Social Change", recommender: "sam-altman" },
    { title: "Sum", recommender: "stephen-fry" },
    { title: "Chokepoint Capitalism", recommender: "stephen-fry" },
    { title: "The Lean Startup", recommender: "steve-blank" },
    { title: "Value Proposition Design", recommender: "steve-blank" },
    { title: "The Innovator's Dilemma", recommender: "steve-blank" },
    { title: "The Big Short", recommender: "sheryl-sandberg" },
    { title: "The Lean Startup", recommender: "sheryl-sandberg" },
    { title: "Conscious Business", recommender: "sheryl-sandberg" },
    { title: "Making Ideas Happen", recommender: "simon-sinek" },
    { title: "Turn the Ship Around!", recommender: "simon-sinek" },
    { title: "Finite and Infinite Games", recommender: "simon-sinek" },
    { title: "Guns, Germs, and Steel", recommender: "simon-sinek" },
    { title: "Give and Take", recommender: "simon-sinek" },
    { title: "Man's Search for Meaning", recommender: "simon-sinek" },
    { title: "Quiet", recommender: "simon-sinek" },
    { title: "It's Better Than It Looks", recommender: "steven-pinker" },
    { title: "The Blind Watchmaker", recommender: "steven-pinker" },
    { title: "Whole Earth Discipline", recommender: "steven-pinker" },
    { title: "The Beginning of Infinity", recommender: "steven-pinker" },
    { title: "Getting Better", recommender: "steven-pinker" },
    { title: "Inside the Tornado", recommender: "steve-jobs" },
    { title: "Only the Paranoid Survive", recommender: "steve-jobs" },
    { title: "The Structure of Scientific Revolutions", recommender: "steve-jobs" },
    { title: "On the Road", recommender: "steve-jobs" },
    { title: "The Dhammapada", recommender: "steve-jobs" },
    { title: "Atlas Shrugged", recommender: "steve-jobs" },
    { title: "Moby Dick", recommender: "steve-jobs" },
    { title: "The Future of Capitalism", recommender: "vinod-khosla" },
    { title: "Atomic Habits", recommender: "vinod-khosla" },
    { title: "Lying", recommender: "vinod-khosla" },
    { title: "Drunk Tank Pink", recommender: "vinod-khosla" },
    { title: "Deep Learning", recommender: "vinod-khosla" },
    { title: "Winners Take All", recommender: "vinod-khosla" },
    { title: "Friday Black", recommender: "vinod-khosla" },
    { title: "Scale", recommender: "vinod-khosla" },
    { title: "Behave", recommender: "vinod-khosla" },
    { title: "21 Lessons for the 21st Century", recommender: "vinod-khosla" },
    { title: "Loonshots", recommender: "vinod-khosla" },
    { title: "Elegant Defense, An", recommender: "vinod-khosla" },
    { title: "How to Change Your Mind", recommender: "vinod-khosla" },
    { title: "Homo Deus", recommender: "vinod-khosla" },
    { title: "The Coddling of the American Mind", recommender: "vinod-khosla" },
    { title: "What You Do Is Who You Are", recommender: "vinod-khosla" },
    { title: "Blitzscaling", recommender: "vinod-khosla" },
    { title: "Sapiens", recommender: "vinod-khosla" },
    { title: "The Master Algorithm", recommender: "vinod-khosla" },
    { title: "Jonathan Livingston Seagull", recommender: "vinod-khosla" },
    { title: "The Score Takes Care of Itself", recommender: "vinod-khosla" },
    { title: "Range", recommender: "vinod-khosla" },
    { title: "The Myth of the Rational Voter", recommender: "vitalik-buterin" },
    { title: "Stubborn Attachments", recommender: "vitalik-buterin" },
    { title: "The Adventures of Huckleberry Finn", recommender: "walter-isaacson" },
    { title: "Tools and Weapons", recommender: "walter-isaacson" },
    { title: "Measure What Matters", recommender: "walter-isaacson" },
    { title: "On the Road", recommender: "walter-isaacson" },
    { title: "The 4-Hour Workweek", recommender: "walter-isaacson" },
    { title: "The Autobiography of Benjamin Franklin", recommender: "walter-isaacson" },
    { title: "The Code Breaker", recommender: "walter-isaacson" },
    { title: "Tap Dancing to Work", recommender: "warren-buffett" },
    { title: "Shoe Dog", recommender: "warren-buffett" },
    { title: "The Little Book of Common Sense Investing", recommender: "warren-buffett" },
    { title: "The Outsiders", recommender: "warren-buffett" },
    { title: "Poor Charlie's Almanack", recommender: "warren-buffett" },
    { title: "The Moment of Lift", recommender: "warren-buffett" },
    { title: "Stress Test", recommender: "warren-buffett" },
    { title: "A Short History of Nearly Everything", recommender: "warren-buffett" },
    { title: "Bull!", recommender: "warren-buffett" },
    { title: "How to Win Friends and Influence People", recommender: "warren-buffett" },
    { title: "What If?", recommender: "werner-vogels" },
    { title: "How to Change Your Mind", recommender: "yuval-noah-harari" },
    { title: "AI Superpowers", recommender: "yuval-noah-harari" },
    { title: "Enlightenment Now", recommender: "yuval-noah-harari" },
    { title: "Brave New World", recommender: "yuval-noah-harari" },
    { title: "The Three-Body Problem", recommender: "yuval-noah-harari" },
    { title: "Liar's Poker", recommender: "tim-ferriss" },
    { title: "The Lessons of History", recommender: "tim-ferriss" },
    { title: "Benjamin Franklin", recommender: "tim-ferriss" },
    { title: "The 22 Immutable Laws of Marketing", recommender: "tim-ferriss" },
    { title: "More Money Than God", recommender: "tim-ferriss" },
    { title: "Emergency", recommender: "tim-ferriss" },
    { title: "Vagabonding", recommender: "tim-ferriss" },
    { title: "Exhalation", recommender: "tim-ferriss" },
    { title: "Checklist Manifesto", recommender: "tim-ferriss" },
    { title: "The Obstacle Is the Way", recommender: "tim-ferriss" },
    { title: "How to Change Your Mind", recommender: "tim-ferriss" },
    { title: "Save The Cat! The Last Book on Screenwriting You'll Ever Need", recommender: "tim-ferriss" },
    { title: "Surely You're Joking, Mr. Feynman!", recommender: "tim-ferriss" },
    { title: "The E-Myth Revisited", recommender: "tim-ferriss" },
    { title: "Ender's Game", recommender: "tim-ferriss" },
    { title: "Getting to Yes", recommender: "tim-ferriss" },
    { title: "The Ride of a Lifetime", recommender: "tim-ferriss" },
    { title: "Open", recommender: "tim-ferriss" },
    { title: "Play It Away", recommender: "tim-ferriss" },
    { title: "Delivering Happiness", recommender: "tim-ferriss" },
    { title: "Blue Ocean Strategy", recommender: "tim-ferriss" },
    { title: "Letters from a Stoic", recommender: "tim-ferriss" },
    { title: "On Writing Well", recommender: "tim-ferriss" },
    { title: "The Smartest Investment Book You'll Ever Read", recommender: "tim-ferriss" },
    { title: "Rework", recommender: "tim-ferriss" },
    { title: "The Magic of Thinking Big", recommender: "tim-ferriss" },
    { title: "Lying", recommender: "tim-ferriss" },
    { title: "Tribe", recommender: "tim-ferriss" },
    { title: "Stranger in a Strange Land", recommender: "tim-ferriss" },
    { title: "Bird by Bird", recommender: "tim-ferriss" },
    { title: "Grit", recommender: "tim-ferriss" },
    { title: "The Hitchhiker's Guide to the Galaxy", recommender: "tim-ferriss" },
    { title: "Principles", recommender: "tim-ferriss" },
    { title: "Fahrenheit 451", recommender: "tim-ferriss" },
    { title: "The Power of Habit", recommender: "tim-ferriss" },
    { title: "Dune", recommender: "tim-ferriss" },
    { title: "Extreme Ownership", recommender: "tim-ferriss" },
    { title: "Awareness", recommender: "tim-ferriss" },
    { title: "Travels with Charley in Search of America", recommender: "tim-ferriss" },
    { title: "Levels of the Game", recommender: "tim-ferriss" },
    { title: "On Writing", recommender: "tim-ferriss" },
    { title: "The Overstory", recommender: "tim-ferriss" },
    { title: "Stories of Your Life and Others", recommender: "tim-ferriss" },
    { title: "Positioning", recommender: "tim-oreilly" },
    { title: "AI Superpowers", recommender: "tim-oreilly" },
    { title: "On Writing Well", recommender: "tim-oreilly" },
    { title: "Tao Te Ching", recommender: "tim-oreilly" },
    { title: "Winners Take All", recommender: "tim-oreilly" },
    { title: "The 22 Immutable Laws of Marketing", recommender: "tim-oreilly" },
    { title: "Alexander Hamilton", recommender: "tim-oreilly" },
    { title: "The Overstory", recommender: "tim-oreilly" },
    { title: "Built to Last", recommender: "tim-oreilly" },
    { title: "The Structure of Scientific Revolutions", recommender: "tim-oreilly" },
    { title: "The Innovator's Dilemma", recommender: "tim-oreilly" },
    { title: "Liar's Poker", recommender: "tim-oreilly" },
    { title: "The Lean Startup", recommender: "tim-oreilly" },
    { title: "Dune", recommender: "tim-oreilly" },
    { title: "Human Compatible", recommender: "tim-oreilly" },
    { title: "Breath", recommender: "tim-oreilly" },
    { title: "The Fountainhead", recommender: "tim-urban" },
    { title: "Atomic Habits", recommender: "tim-urban" },
    { title: "Hit Makers", recommender: "tim-urban" },
    { title: "The Three-Body Problem", recommender: "tim-urban" },
    { title: "Originals", recommender: "tim-urban" },
    { title: "Mindset", recommender: "tobi-lutke" },
    { title: "High Output Management", recommender: "tobi-lutke" },
    { title: "Drive", recommender: "tobi-lutke" },
    { title: "The Courage to Be Disliked", recommender: "tobi-lutke" },
    { title: "The Box", recommender: "tobi-lutke" },
    { title: "Influence", recommender: "tobi-lutke" },
    { title: "Tuxedo Park", recommender: "tobi-lutke" },
    { title: "Meditations", recommender: "tobi-lutke" },
    { title: "Snow Crash", recommender: "tobi-lutke" },
    { title: "The Three-Body Problem", recommender: "tobi-lutke" },
    { title: "Why We Sleep", recommender: "tobi-lutke" },
    { title: "A Guide to the Good Life", recommender: "tobi-lutke" },
    { title: "Permutation City", recommender: "tobi-lutke" },
    { title: "The Evolution of Everything", recommender: "tobi-lutke" },
    { title: "Grit", recommender: "tobi-lutke" },
    { title: "Open", recommender: "tobi-lutke" },
    { title: "Scale", recommender: "tobi-lutke" },
    { title: "Finite and Infinite Games", recommender: "tobi-lutke" },
    { title: "Hackers", recommender: "tobi-lutke" },
    { title: "How to Fail at Almost Everything and Still Win Big", recommender: "tobi-lutke" },
    { title: "What's Our Problem?", recommender: "tobi-lutke" },
    { title: "Play It Away", recommender: "tony-robbins" },
    { title: "Principles", recommender: "tony-robbins" },
    { title: "The 15 Commitments of Conscious Leadership", recommender: "tony-robbins" },
    { title: "Behind the Cloud", recommender: "tony-robbins" },
    { title: "Man's Search for Meaning", recommender: "tony-robbins" },
    { title: "Alexander Hamilton", recommender: "travis-kalanick" },
    { title: "The Fountainhead", recommender: "travis-kalanick" },
    { title: "Atlas Shrugged", recommender: "travis-kalanick" },
    { title: "The Founders", recommender: "elon-musk" },
    { title: "Daily Rituals", recommender: "elon-musk" },
    { title: "Masters of Doom", recommender: "elon-musk" },
    { title: "Makers", recommender: "elon-musk" },
    { title: "Einstein", recommender: "elon-musk" },
    { title: "The Moon Is a Harsh Mistress", recommender: "elon-musk" },
    { title: "Genome  First American Edition edition by M. Ridley", recommender: "mark-zuckerberg" },
    { title: "Good to Great", recommender: "jeff-bezos" },
    { title: "Mythical Man-Month, The", recommender: "jeff-bezos" },
    { title: "Radical Candor", recommender: "sheryl-sandberg" },
    { title: "Trillion Dollar Coach", recommender: "sheryl-sandberg" },
    { title: "Blitzscaling", recommender: "sheryl-sandberg" },
    { title: "Drop the Ball", recommender: "sheryl-sandberg" },
    { title: "Option B", recommender: "sheryl-sandberg" },
    { title: "Just the Funny Parts", recommender: "sheryl-sandberg" },
    { title: "Thrive", recommender: "sheryl-sandberg" },
    { title: "Unsafe Thinking", recommender: "sheryl-sandberg" },
    { title: "The Start-Up of You", recommender: "sheryl-sandberg" },
    { title: "The Intelligent Investor Rev Ed. The Definitive Book on Value Investing", recommender: "warren-buffett" },
    { title: "Leadership", recommender: "warren-buffett" },
    { title: "Security Analysis, Sixth Edition", recommender: "warren-buffett" },
    { title: "How to Invest", recommender: "bill-gates" },
    { title: "Superintelligence", recommender: "bill-gates" },
    { title: "Why Nations Fail", recommender: "bill-gates" },
    { title: "It's Better Than It Looks", recommender: "bill-gates" },
    { title: "The Singularity Is Nearer", recommender: "bill-gates" },
    { title: "The Inner Game Of Tennis", recommender: "bill-gates" },
    { title: "The Innovator's Dilemma", recommender: "steve-jobs" },
    { title: "When Breath Becomes Air", recommender: "tim-cook" },
    { title: "Trillion Dollar Coach", recommender: "tim-cook" },
    { title: "No Rules Rules", recommender: "satya-nadella" },
    { title: "The Soul of a New Machine", recommender: "satya-nadella" },
    { title: "The Moment of Lift", recommender: "satya-nadella" },
    { title: "AI Superpowers", recommender: "satya-nadella" },
    { title: "Leonardo da Vinci", recommender: "satya-nadella" },
    { title: "Evicted", recommender: "satya-nadella" },
    { title: "How to Invest", recommender: "satya-nadella" },
    { title: "AI 2041", recommender: "satya-nadella" },
    { title: "Thinking, Fast and Slow", recommender: "satya-nadella" },
    { title: "Zero to One", recommender: "satya-nadella" },
    { title: "The Hard Thing About Hard Things", recommender: "satya-nadella" },
    { title: "Hit Refresh", recommender: "satya-nadella" },
    { title: "Deep Learning", recommender: "satya-nadella" },
    { title: "The History of the Peloponnesian War  Revised edition by Thucydides,M. I. Finley,R. Warner", recommender: "satya-nadella" },
    { title: "Eat to Beat Your Diet", recommender: "tony-robbins" },
    { title: "The Latte Factor", recommender: "tony-robbins" },
    { title: "The Alchemist", recommender: "tony-robbins" },
    { title: "AS A MAN THINKETH", recommender: "tony-robbins" },
    { title: "Sapiens", recommender: "tony-robbins" },
    { title: "Tools Of Titans", recommender: "tony-robbins" },
    { title: "Think and Grow Rich", recommender: "tony-robbins" },
    { title: "The Untethered Soul", recommender: "tony-robbins" },
    { title: "Long Walk To Freedom", recommender: "tony-robbins" },
    { title: "Crush It!", recommender: "tony-robbins" },
    { title: "The Prophet", recommender: "tony-robbins" },
    { title: "Bold", recommender: "tony-robbins" },
    { title: "The Mastery of Love", recommender: "tony-robbins" },
    { title: "Abundance", recommender: "tony-robbins" },
    { title: "Getting Everything You Can Out of All You've Got", recommender: "tony-robbins" },
    { title: "The Singularity Is Nearer", recommender: "tony-robbins" },
    { title: "Snow Crash", recommender: "larry-page" },
    { title: "Surely You're Joking, Mr. Feynman!", recommender: "larry-page" },
    { title: "How I Built This", recommender: "mark-cuban" },
    { title: "The Power of Broke", recommender: "mark-cuban" },
    { title: "AI 2041", recommender: "mark-cuban" },
    { title: "The Black Swan", recommender: "peter-thiel" },
    { title: "The Sovereign Individual", recommender: "peter-thiel" },
    { title: "The Right Stuff", recommender: "peter-thiel" },
    { title: "The Diamond Age, or, A Young Lady's Illustrated Primer", recommender: "peter-thiel" },
    { title: "What It Takes", recommender: "eric-schmidt" },
    { title: "Secrets of Sand Hill Road", recommender: "eric-schmidt" },
    { title: "How to Change", recommender: "eric-schmidt" },
    { title: "What's Your Problem?", recommender: "eric-schmidt" },
    { title: "Outliers", recommender: "eric-schmidt" },
    { title: "Crush It!", recommender: "eric-schmidt" },
    { title: "Machine, Platform, Crowd", recommender: "eric-schmidt" },
    { title: "Bold", recommender: "eric-schmidt" },
    { title: "Tribal Leadership", recommender: "eric-schmidt" },
    { title: "The Industries of the Future", recommender: "eric-schmidt" },
    { title: "The $100 Startup", recommender: "eric-schmidt" },
    { title: "Peak", recommender: "eric-schmidt" },
    { title: "The Happiness Hypothesis", recommender: "eric-schmidt" },
    { title: "Creativity, Inc.", recommender: "alexis-ohanian" },
    { title: "How to Win Friends and Influence People", recommender: "alexis-ohanian" },
    { title: "American Kingpin", recommender: "alexis-ohanian" },
    { title: "Hooked", recommender: "alexis-ohanian" },
    { title: "The Minimalist Entrepreneur", recommender: "alexis-ohanian" },
    { title: "Snow Crash", recommender: "alexis-ohanian" },
    { title: "Superforecasting", recommender: "alexis-ohanian" },
    { title: "Traction", recommender: "alexis-ohanian" },
    { title: "High Growth Handbook", recommender: "alexis-ohanian" },
    { title: "So Good They Can't Ignore You", recommender: "alexis-ohanian" },
    { title: "Hatching Twitter", recommender: "alexis-ohanian" },
    { title: "Eat to Beat Your Diet", recommender: "richard-branson" },
    { title: "Trailblazer", recommender: "richard-branson" },
    { title: "Long Walk To Freedom", recommender: "richard-branson" },
    { title: "AS A MAN THINKETH", recommender: "tim-ferriss" },
    { title: "Anything You Want", recommender: "tim-ferriss" },
    { title: "Crush It!", recommender: "tim-ferriss" },
    { title: "Atlas Shrugged", recommender: "tim-ferriss" },
    { title: "A Geek in Japan", recommender: "tim-ferriss" },
    { title: "Antifragile", recommender: "tim-ferriss" },
    { title: "Abundance", recommender: "tim-ferriss" },
    { title: "A Guide to the Good Life", recommender: "tim-ferriss" },
    { title: "Au Contraire", recommender: "tim-ferriss" },
    { title: "Built to Last", recommender: "jack-ma" },
    { title: "Makers", recommender: "jack-ma" },
    { title: "The Long Tail", recommender: "jack-ma" },
    { title: "Here Comes Everybody", recommender: "jack-ma" },
    { title: "How to Win Friends and Influence People", recommender: "daymond-john" },
    { title: "Sell It Like Serhant", recommender: "daymond-john" },
    { title: "The Power of Broke", recommender: "daymond-john" },
    { title: "Think and Grow Rich", recommender: "daymond-john" },
    { title: "Essentialism", recommender: "daymond-john" },
    { title: "Super Freakonomics", recommender: "daymond-john" },
    { title: "Titan The Life Of John D", recommender: "charlie-munger" },
    { title: "Genome  First American Edition edition by M. Ridley", recommender: "charlie-munger" },
    { title: "Sapiens", recommender: "dan-ariely" },
    { title: "Contagious", recommender: "dan-ariely" },
    { title: "Influence", recommender: "dan-ariely" },
    { title: "Give and Take", recommender: "dan-ariely" },
    { title: "Makers", recommender: "dan-ariely" },
    { title: "Willpower", recommender: "dan-ariely" },
    { title: "Nudge", recommender: "dan-ariely" },
    { title: "The Creative Act", recommender: "seth-godin" },
    { title: "Think Like a Rocket Scientist", recommender: "seth-godin" },
    { title: "The Entrepreneur Roller Coaster", recommender: "seth-godin" },
    { title: "The Culture Code", recommender: "seth-godin" },
    { title: "The Magic of Thinking Big", recommender: "seth-godin" },
    { title: "Chokepoint Capitalism", recommender: "seth-godin" },
    { title: "Deep Work", recommender: "seth-godin" },
    { title: "How to Change", recommender: "seth-godin" },
    { title: "How to Decide", recommender: "seth-godin" },
    { title: "The Happiness Equation", recommender: "seth-godin" },
    { title: "Digital Minimalism", recommender: "seth-godin" },
    { title: "Peak", recommender: "seth-godin" },
    { title: "Pivot", recommender: "seth-godin" },
    { title: "The $100 Startup", recommender: "seth-godin" },
    { title: "The Referral Engine", recommender: "seth-godin" },
    { title: "The Red Queen", recommender: "seth-godin" },
    { title: "How We Decide", recommender: "seth-godin" },
    { title: "The War of Art Winning the Inner Creative Battle", recommender: "seth-godin" },
    { title: "Here Comes Everybody", recommender: "seth-godin" },
    { title: "Competing Against Luck", recommender: "jack-dorsey" },
    { title: "Tao Te Ching", recommender: "jack-dorsey" },
    { title: "The Checklist Manifesto", recommender: "jack-dorsey" },
    { title: "Spiritual Enlightenment, the Damnedest Thing", recommender: "jack-dorsey" },
    { title: "The Boy Who Harnessed the Wind", recommender: "jack-dorsey" },
    { title: "The Startup Community Way", recommender: "ben-horowitz" },
    { title: "My Years With General Motors", recommender: "ben-horowitz" },
    { title: "Good to Great", recommender: "drew-houston" },
    { title: "Built to Last", recommender: "drew-houston" },
    { title: "Secrets of Sand Hill Road", recommender: "sam-altman" },
    { title: "The Making of a Manager", recommender: "sam-altman" },
    { title: "A Pattern Language", recommender: "sam-altman" },
    { title: "Thinking, Fast and Slow", recommender: "sam-altman" },
    { title: "Man's Search for Meaning", recommender: "sam-altman" },
    { title: "Zero to One", recommender: "sam-altman" },
    { title: "The Score Takes Care of Itself", recommender: "sam-altman" },
    { title: "Einstein", recommender: "sam-altman" },
    { title: "Winning", recommender: "sam-altman" },
    { title: "Brave New World", recommender: "sam-altman" },
    { title: "Endurance", recommender: "sam-altman" },
    { title: "The Old Way", recommender: "sam-altman" },
    { title: "The Origin of Consciousness in the Breakdown of the Bicameral Mind", recommender: "sam-altman" },
    { title: "Solution Selling", recommender: "sam-altman" },
    { title: "Dealers of Lightning", recommender: "sam-altman" },
    { title: "Foundation", recommender: "sam-altman" },
    { title: "How I Built This", recommender: "simon-sinek" },
    { title: "The Latte Factor", recommender: "simon-sinek" },
    { title: "Good to Great", recommender: "simon-sinek" },
    { title: "The 7 Habits of Highly Effective People", recommender: "simon-sinek" },
    { title: "Outliers", recommender: "simon-sinek" },
    { title: "The E-Myth Revisited", recommender: "simon-sinek" },
    { title: "The 4-Hour Workweek", recommender: "simon-sinek" },
    { title: "The Black Swan", recommender: "simon-sinek" },
    { title: "The Tipping Point", recommender: "simon-sinek" },
    { title: "The Wisdom of Crowds", recommender: "simon-sinek" },
    { title: "The Monk and the Riddle", recommender: "simon-sinek" },
    { title: "Good to Great", recommender: "steve-blank" },
    { title: "The Art of War", recommender: "steve-blank" },
    { title: "The Hard Thing About Hard Things", recommender: "steve-blank" },
    { title: "Built to Last", recommender: "steve-blank" },
    { title: "Business Model Generation", recommender: "steve-blank" },
    { title: "Talking to Humans", recommender: "steve-blank" },
    { title: "Crossing the Chasm", recommender: "steve-blank" },
    { title: "My Years With General Motors", recommender: "steve-blank" },
    { title: "The Book of Five Rings", recommender: "steve-blank" },
    { title: "The Innovator's Solution", recommender: "steve-blank" },
    { title: "The Tipping Point", recommender: "steve-blank" },
    { title: "Inside the Tornado", recommender: "steve-blank" },
    { title: "Dealing with Darwin", recommender: "steve-blank" },
    { title: "Solution Selling", recommender: "steve-blank" },
    { title: "The Four Steps to the Epiphany", recommender: "steve-blank" },
    { title: "The Design Of Everyday Things", recommender: "marissa-mayer" },
    { title: "Sapiens", recommender: "daniel-kahneman" },
    { title: "Human Compatible", recommender: "daniel-kahneman" },
    { title: "Homo Deus", recommender: "daniel-kahneman" },
    { title: "Misbehaving", recommender: "daniel-kahneman" },
    { title: "Thinking, Fast and Slow", recommender: "daniel-kahneman" },
    { title: "Skin in the Game", recommender: "daniel-kahneman" },
    { title: "Thinking in Bets", recommender: "daniel-kahneman" },
    { title: "Loonshots", recommender: "daniel-kahneman" },
    { title: "Influence", recommender: "daniel-kahneman" },
    { title: "The Power of Habit", recommender: "daniel-kahneman" },
    { title: "Fooled by Randomness", recommender: "daniel-kahneman" },
    { title: "The Black Swan", recommender: "daniel-kahneman" },
    { title: "Scarcity", recommender: "daniel-kahneman" },
    { title: "Nudge", recommender: "daniel-kahneman" },
    { title: "Born Standing Up", recommender: "daniel-kahneman" },
    { title: "The Better Angels of Our Nature", recommender: "daniel-kahneman" },
    { title: "Tiny Habits", recommender: "guy-kawasaki" },
    { title: "The Subtle Art of Not Giving a F*ck", recommender: "guy-kawasaki" },
    { title: "Mindset", recommender: "guy-kawasaki" },
    { title: "Quiet", recommender: "guy-kawasaki" },
    { title: "Crossing the Chasm", recommender: "guy-kawasaki" },
    { title: "Show and Tell", recommender: "guy-kawasaki" },
    { title: "Together", recommender: "guy-kawasaki" },
    { title: "The Referral Engine", recommender: "guy-kawasaki" },
    { title: "Seeking Wisdom", recommender: "guy-kawasaki" },
    { title: "What Really Makes America Great", recommender: "guy-kawasaki" },
    { title: "Being Mortal", recommender: "malcolm-gladwell" },
    { title: "Misbehaving", recommender: "malcolm-gladwell" },
    { title: "The Innovator's Dilemma", recommender: "malcolm-gladwell" },
    { title: "Fooled by Randomness", recommender: "malcolm-gladwell" },
    { title: "Super Freakonomics", recommender: "malcolm-gladwell" },
    { title: "The Gene", recommender: "reid-hoffman" },
    { title: "Snow Crash", recommender: "reid-hoffman" },
    { title: "Zero to One", recommender: "reid-hoffman" },
    { title: "Essentialism", recommender: "reid-hoffman" },
    { title: "The True Believer", recommender: "reid-hoffman" },
    { title: "WTF?", recommender: "reid-hoffman" },
    { title: "Machine, Platform, Crowd", recommender: "reid-hoffman" },
    { title: "The Industries of the Future", recommender: "reid-hoffman" },
    { title: "The Moral Animal", recommender: "reid-hoffman" },
    { title: "Sell It Like Serhant", recommender: "gary-vaynerchuk" },
    { title: "The Power of Broke", recommender: "gary-vaynerchuk" },
    { title: "Steve Jobs", recommender: "gary-vaynerchuk" },
    { title: "Bad Blood", recommender: "andrew-chen" },
    { title: "What You Do Is Who You Are", recommender: "andrew-chen" },
    { title: "Dune", recommender: "andrew-chen" },
    { title: "Hooked", recommender: "andrew-chen" },
    { title: "The Four Steps to the Epiphany", recommender: "andrew-chen" },
    { title: "The Hard Thing About Hard Things", recommender: "andrew-chen" },
    { title: "The Design Of Everyday Things", recommender: "andrew-chen" },
    { title: "The Inmates Are Running the Asylum", recommender: "andrew-chen" },
    { title: "The Innovator's Dilemma", recommender: "andrew-chen" },
    { title: "Crossing the Chasm", recommender: "andrew-chen" },
    { title: "High Output Management", recommender: "andrew-chen" },
    { title: "Antifragile", recommender: "andrew-chen" },
    { title: "The Lean Startup", recommender: "andrew-chen" },
    { title: "Growth Hacker Marketing", recommender: "andrew-chen" },
    { title: "Founders at Work", recommender: "andrew-chen" },
    { title: "Mythical Man-Month, The", recommender: "andrew-chen" },
    { title: "Startup Rising", recommender: "andrew-chen" },
    { title: "The Diamond Age, or, A Young Lady's Illustrated Primer", recommender: "andrew-chen" },
    { title: "Without You, There Is No Us", recommender: "andrew-chen" },
    { title: "The Three-Body Problem", recommender: "andrew-chen" },
    { title: "The Master Switch", recommender: "andrew-chen" },
    { title: "On Writing", recommender: "ken-norton" },
    { title: "Creativity, Inc.", recommender: "ken-norton" },
    { title: "Hooked", recommender: "ken-norton" },
    { title: "Getting Things Done", recommender: "ken-norton" },
    { title: "How to Lie with Statistics", recommender: "ken-norton" },
    { title: "The Lean Product Playbook", recommender: "ken-norton" },
    { title: "Sprint", recommender: "ken-norton" },
    { title: "Work Rules!", recommender: "ken-norton" },
    { title: "Competing Against Luck", recommender: "ken-norton" },
    { title: "Thinking, Fast and Slow", recommender: "ken-norton" },
    { title: "The Hard Thing About Hard Things", recommender: "ken-norton" },
    { title: "The Design Of Everyday Things", recommender: "ken-norton" },
    { title: "Quiet", recommender: "ken-norton" },
    { title: "Predictably Irrational, Revised and Expanded Edition", recommender: "ken-norton" },
    { title: "Don't Make Me Think, Revisited", recommender: "ken-norton" },
    { title: "Crossing the Chasm", recommender: "ken-norton" },
    { title: "High Output Management", recommender: "ken-norton" },
    { title: "The Lean Startup", recommender: "ken-norton" },
    { title: "The Innovator's Solution", recommender: "ken-norton" },
    { title: "In the Plex", recommender: "ken-norton" },
    { title: "Mythical Man-Month, The", recommender: "ken-norton" },
    { title: "Inside the Tornado", recommender: "ken-norton" },
    { title: "The Halo Effect", recommender: "ken-norton" },
    { title: "Positioning", recommender: "ken-norton" },
    { title: "Getting to Yes", recommender: "ken-norton" },
    { title: "Steve Jobs", recommender: "ken-norton" },
    { title: "The Innovator's Dilemma", recommender: "ken-norton" },
    { title: "How to Win Friends and Influence People", recommender: "nir-eyal" },
    { title: "Think Like a Rocket Scientist", recommender: "nir-eyal" },
    { title: "The Making of a Manager", recommender: "nir-eyal" },
    { title: "Hooked", recommender: "nir-eyal" },
    { title: "The Lean Product Playbook", recommender: "nir-eyal" },
    { title: "Sprint", recommender: "nir-eyal" },
    { title: "The Art of Game Design", recommender: "nir-eyal" },
    { title: "Outliers", recommender: "nir-eyal" },
    { title: "Traction", recommender: "nir-eyal" },
    { title: "Value Proposition Design", recommender: "nir-eyal" },
    { title: "Influence", recommender: "nir-eyal" },
    { title: "Business Model Generation", recommender: "nir-eyal" },
    { title: "The Design Of Everyday Things", recommender: "nir-eyal" },
    { title: "Switch", recommender: "nir-eyal" },
    { title: "Made to Stick", recommender: "nir-eyal" },
    { title: "The Innovator's Dilemma", recommender: "nir-eyal" },
    { title: "Don't Make Me Think, Revisited", recommender: "nir-eyal" },
    { title: "Crossing the Chasm", recommender: "nir-eyal" },
    { title: "Product-Led Onboarding", recommender: "nir-eyal" },
    { title: "The Power of Habit", recommender: "nir-eyal" },
    { title: "The Lean Startup", recommender: "nir-eyal" },
    { title: "The Willpower Instinct", recommender: "nir-eyal" },
    { title: "Drive", recommender: "nir-eyal" },
    { title: "Growth Hacker Marketing", recommender: "nir-eyal" },
    { title: "The Art of SEO", recommender: "nir-eyal" },
    { title: "Rocket Surgery Made Easy", recommender: "nir-eyal" },
    { title: "Hackers & Painters", recommender: "nir-eyal" },
    { title: "Don't Shoot the Dog!", recommender: "nir-eyal" },
    { title: "What Technology Wants", recommender: "nir-eyal" },
    { title: "Creativity, Inc.", recommender: "julie-zhuo" },
    { title: "Being Mortal", recommender: "julie-zhuo" },
    { title: "The Hard Thing About Hard Things", recommender: "julie-zhuo" },
    { title: "Lean In", recommender: "julie-zhuo" },
    { title: "How to Talk So Kids Will Listen & Listen So Kids Will Talk", recommender: "jeff-atwood" },
    { title: "The Design Of Everyday Things", recommender: "jeff-atwood" },
    { title: "Don't Make Me Think, Revisited", recommender: "jeff-atwood" },
    { title: "Envisioning Information", recommender: "jeff-atwood" },
    { title: "Visual Explanations", recommender: "jeff-atwood" },
    { title: "Creativity, Inc.", recommender: "jim-collins" },
    { title: "Leadership", recommender: "jim-collins" },
    { title: "Becoming Steve Jobs", recommender: "jim-collins" },
    { title: "Smarter Faster Better", recommender: "jim-collins" },
    { title: "Influence", recommender: "jim-collins" },
    { title: "The Second World War", recommender: "jim-collins" },
    { title: "The Ride of a Lifetime", recommender: "michael-bloomberg" },
    { title: "Thirst", recommender: "michael-bloomberg" },
    { title: "Brotopia", recommender: "michael-bloomberg" },
    { title: "Frenemies", recommender: "michael-bloomberg" },
    { title: "The Start-Up of You", recommender: "michael-bloomberg" },
    { title: "Contagious", recommender: "vinod-khosla" },
    { title: "Superforecasting", recommender: "vinod-khosla" },
    { title: "The Design Of Everyday Things", recommender: "vinod-khosla" },
    { title: "Made to Stick", recommender: "vinod-khosla" },
    { title: "Predictably Irrational, Revised and Expanded Edition", recommender: "vinod-khosla" },
    { title: "High Output Management", recommender: "vinod-khosla" },
    { title: "The Lean Startup", recommender: "vinod-khosla" },
    { title: "The Checklist Manifesto", recommender: "vinod-khosla" },
    { title: "The Black Swan", recommender: "vinod-khosla" },
    { title: "Only the Paranoid Survive", recommender: "vinod-khosla" },
    { title: "How We Decide", recommender: "vinod-khosla" },
    { title: "Save The Cat! The Last Book on Screenwriting You'll Ever Need", recommender: "vinod-khosla" },
    { title: "The Success Equation", recommender: "vinod-khosla" },
    { title: "The Second Machine Age", recommender: "vinod-khosla" },
    { title: "Expert Political Judgment", recommender: "vinod-khosla" },
    { title: "Nudge", recommender: "vinod-khosla" },
    { title: "The Splendid and the Vile", recommender: "arnold-schwarzenegger" },
    { title: "Think Again", recommender: "arnold-schwarzenegger" },
    { title: "The Bully Pulpit", recommender: "arnold-schwarzenegger" },
    { title: "Your Next Five Moves", recommender: "brian-tracy" },
    { title: "The Sales Manager's Guide to Greatness", recommender: "brian-tracy" },
    { title: "Pivot", recommender: "brian-tracy" },
    { title: "The Effective Executive", recommender: "brian-tracy" },
    { title: "The Ultimate Sales Machine", recommender: "brian-tracy" },
    { title: "Built to Last", recommender: "brian-tracy" },
    { title: "Flow", recommender: "brian-tracy" },
    { title: "The Art of SEO", recommender: "brian-tracy" },
    { title: "Getting Everything You Can Out of All You've Got", recommender: "brian-tracy" },
    { title: "Economics in One Lesson", recommender: "brian-tracy" },
    { title: "The Creative Act", recommender: "ryan-holiday" },
    { title: "Titan The Life Of John D", recommender: "ryan-holiday" },
    { title: "Shoe Dog", recommender: "ryan-holiday" },
    { title: "Sell It Like Serhant", recommender: "ryan-holiday" },
    { title: "Indistractable", recommender: "ryan-holiday" },
    { title: "Digital Minimalism", recommender: "ryan-holiday" },
    { title: "The Art of War", recommender: "ryan-holiday" },
    { title: "Antifragile", recommender: "ryan-holiday" },
    { title: "Benjamin Franklin", recommender: "ryan-holiday" },
    { title: "Fooled by Randomness", recommender: "ryan-holiday" },
    { title: "Smartcuts", recommender: "ryan-holiday" },
    { title: "The History of the Peloponnesian War  Revised edition by Thucydides,M. I. Finley,R. Warner", recommender: "ryan-holiday" },
    { title: "Edison", recommender: "ryan-holiday" },
    { title: "Hateship, Friendship, Courtship, Loveship, Marriage", recommender: "ryan-holiday" },
    { title: "Don't Think Of An Elephant!/ How Democrats And Progressives Can Win", recommender: "ryan-holiday" },
    { title: "Nudge", recommender: "ryan-holiday" },
    { title: "The War of Art Winning the Inner Creative Battle", recommender: "ryan-holiday" },
    { title: "Good to Great", recommender: "max-levchin" },
    { title: "Predictably Irrational, Revised and Expanded Edition", recommender: "max-levchin" },
    { title: "Work Rules!", recommender: "daniel-pink" },
    { title: "Mindset", recommender: "daniel-pink" },
    { title: "Flow", recommender: "daniel-pink" },
    { title: "The Talent Code", recommender: "daniel-pink" },
    { title: "The Sports Gene", recommender: "daniel-pink" },
    { title: "The War of Art Winning the Inner Creative Battle", recommender: "daniel-pink" },
    { title: "Getting Things Done", recommender: "david-allen" },
    { title: "Smarter Faster Better", recommender: "david-allen" },
    { title: "Give and Take", recommender: "david-allen" },
    { title: "Do the Work", recommender: "david-allen" },
    { title: "Show and Tell", recommender: "david-allen" },
    { title: "Thrive", recommender: "david-allen" },
    { title: "Don't Shoot the Dog!", recommender: "david-allen" },
    { title: "Steve Jobs", recommender: "david-allen" },
    { title: "How to Win Friends and Influence People", recommender: "john-doerr" },
    { title: "Good to Great", recommender: "john-doerr" },
    { title: "Work Rules!", recommender: "john-doerr" },
    { title: "Connecting the Dots", recommender: "john-doerr" },
    { title: "Steve Jobs", recommender: "john-doerr" },
    { title: "The Lean Startup", recommender: "ryan-hoover" },
    { title: "The Making of a Manager", recommender: "ev-williams" },
    { title: "Sprint", recommender: "ev-williams" },
    { title: "Delivering Happiness", recommender: "ev-williams" },
    { title: "The Latte Factor", recommender: "ken-blanchard" },
    { title: "Good to Great", recommender: "ken-blanchard" },
    { title: "The Happiness Equation", recommender: "ken-blanchard" },
    { title: "The Sales Manager's Guide to Greatness", recommender: "ken-blanchard" },
    { title: "The Score Takes Care of Itself", recommender: "ken-blanchard" },
    { title: "The Design Of Everyday Things", recommender: "joel-spolsky" },
    { title: "The Inmates Are Running the Asylum", recommender: "joel-spolsky" },
    { title: "Don't Make Me Think, Revisited", recommender: "joel-spolsky" },
    { title: "The Pragmatic Programmer", recommender: "joel-spolsky" },
    { title: "Mythical Man-Month, The", recommender: "joel-spolsky" },
    { title: "Hackers & Painters", recommender: "joel-spolsky" },
    { title: "Peopleware", recommender: "joel-spolsky" },
    { title: "Just for Fun", recommender: "joel-spolsky" },
    { title: "The Fountainhead", recommender: "fred-wilson" },
    { title: "The Soul of a New Machine", recommender: "fred-wilson" },
    { title: "Siddhartha", recommender: "fred-wilson" },
    { title: "Where the Wild Things Are", recommender: "fred-wilson" },
    { title: "Snow Crash", recommender: "fred-wilson" },
    { title: "Setting the Table", recommender: "fred-wilson" },
    { title: "The Hard Thing About Hard Things", recommender: "fred-wilson" },
    { title: "Talking to Humans", recommender: "fred-wilson" },
    { title: "Atlas Shrugged", recommender: "fred-wilson" },
    { title: "Endurance", recommender: "fred-wilson" },
    { title: "One Hundred Years of Solitude", recommender: "fred-wilson" },
    { title: "Jonathan Livingston Seagull", recommender: "fred-wilson" },
    { title: "Zen and the Art of Motorcycle Maintenance", recommender: "fred-wilson" },
    { title: "Think Again", recommender: "hunter-walk" },
    { title: "What You Do Is Who You Are", recommender: "hunter-walk" },
    { title: "Super Pumped", recommender: "hunter-walk" },
    { title: "The Box", recommender: "hunter-walk" },
    { title: "The Righteous Mind", recommender: "hunter-walk" },
    { title: "Friday Black", recommender: "hunter-walk" },
    { title: "The Selfish Gene", recommender: "hunter-walk" },
    { title: "The Startup Community Way", recommender: "hunter-walk" },
    { title: "Flow", recommender: "hunter-walk" },
    { title: "Founders at Work", recommender: "hunter-walk" },
    { title: "Exhalation", recommender: "hunter-walk" },
    { title: "Don't Think Of An Elephant!/ How Democrats And Progressives Can Win", recommender: "hunter-walk" },
    { title: "Taking the Work Out of Networking", recommender: "hunter-walk" },
    { title: "Season of the Witch", recommender: "hunter-walk" },
    { title: "Zero to One", recommender: "casey-neistat" },
    { title: "Essentialism", recommender: "casey-neistat" },
    { title: "The Minimalist Entrepreneur", recommender: "jason-fried" },
    { title: "Quiet", recommender: "jason-fried" },
    { title: "Seeking Wisdom", recommender: "jason-fried" },
    { title: "Rework", recommender: "jason-fried" },
    { title: "Turn the Ship Around!", recommender: "jason-fried" },
    { title: "The Talent Code", recommender: "jason-fried" },
    { title: "Remote", recommender: "jason-fried" },
    { title: "Connecting the Dots", recommender: "aaron-levie" },
    { title: "Brotopia", recommender: "aaron-levie" },
    { title: "How to Castrate a Bull", recommender: "aaron-levie" },
    { title: "Hard Drive", recommender: "aaron-levie" },
    { title: "Trailblazer", recommender: "susan-wojcicki" },
    { title: "Product-Led Onboarding", recommender: "sean-ellis" },
    { title: "The Great CEO Within", recommender: "naval-ravikant" },
    { title: "Thinking, Fast and Slow", recommender: "naval-ravikant" },
    { title: "The Innovator's Dilemma", recommender: "naval-ravikant" },
    { title: "The Innovator's Dilemma", recommender: "andy-grove" },
    { title: "Your Next Five Moves", recommender: "ray-dalio" },
    { title: "What It Takes", recommender: "ray-dalio" },
    { title: "Trailblazer", recommender: "ray-dalio" },
    { title: "AI 2041", recommender: "ray-dalio" },
    { title: "The Great CEO Within", recommender: "steve-huffman" },
    { title: "Why Nations Fail", recommender: "steven-levitt" },
    { title: "Nudge", recommender: "steven-levitt" },
    { title: "Bold", recommender: "michael-dell" },
    { title: "How to Decide", recommender: "marc-andreessen" },
    { title: "Connecting the Dots", recommender: "marc-andreessen" },
    { title: "The Inevitable", recommender: "marc-andreessen" },
    { title: "Antifragile", recommender: "marc-andreessen" },
    { title: "Startup Rising", recommender: "marc-andreessen" },
    { title: "How to Castrate a Bull", recommender: "marc-andreessen" },
    { title: "In the Plex", recommender: "jessica-livingstone" },
    { title: "The Success Equation", recommender: "jessica-livingstone" },
    { title: "Red Notice", recommender: "eric-ries" },
    { title: "What You Do Is Who You Are", recommender: "eric-ries" },
    { title: "Secrets of Sand Hill Road", recommender: "eric-ries" },
    { title: "Sprint", recommender: "eric-ries" },
    { title: "Remote Work Revolution", recommender: "eric-ries" },
    { title: "WTF?", recommender: "eric-ries" },
    { title: "The Lean Startup", recommender: "eric-ries" },
    { title: "Makers", recommender: "eric-ries" },
    { title: "The Startup Way", recommender: "eric-ries" },
    { title: "Nudge", recommender: "eric-ries" },
    { title: "How to Win Friends and Influence People", recommender: "joel-gascoigne" },
    { title: "Zero to One", recommender: "joel-gascoigne" },
    { title: "The 7 Habits of Highly Effective People", recommender: "joel-gascoigne" },
    { title: "Tao Te Ching", recommender: "joel-gascoigne" },
    { title: "Setting the Table", recommender: "joel-gascoigne" },
    { title: "The Hard Thing About Hard Things", recommender: "joel-gascoigne" },
    { title: "The Score Takes Care of Itself", recommender: "joel-gascoigne" },
    { title: "Delivering Happiness", recommender: "joel-gascoigne" },
    { title: "The Obstacle Is the Way", recommender: "joel-gascoigne" },
    { title: "Reboot", recommender: "joel-gascoigne" },
    { title: "Quiet", recommender: "joel-gascoigne" },
    { title: "The Mastery of Love", recommender: "joel-gascoigne" },
    { title: "The 4-Hour Workweek", recommender: "joel-gascoigne" },
    { title: "The Lean Startup", recommender: "joel-gascoigne" },
    { title: "Founders at Work", recommender: "joel-gascoigne" },
    { title: "Let My People Go Surfing", recommender: "joel-gascoigne" },
    { title: "The Autobiography of Benjamin Franklin", recommender: "joel-gascoigne" },
    { title: "Vagabonding", recommender: "joel-gascoigne" },
    { title: "Traction", recommender: "joel-gascoigne" },
    { title: "The Alchemist", recommender: "joel-gascoigne" },
    { title: "The Power of Full Engagement", recommender: "joel-gascoigne" },
    { title: "Happiness", recommender: "joel-gascoigne" },
    { title: "The Monk and the Riddle", recommender: "joel-gascoigne" },
    { title: "The Four Agreements", recommender: "joel-gascoigne" },
    { title: "The Soul of a New Machine", recommender: "paul-graham" },
    { title: "Zen and the Art of Motorcycle Maintenance", recommender: "paul-graham" },
    { title: "The Structure of Scientific Revolutions", recommender: "paul-graham" },
    { title: "Just for Fun", recommender: "linus-torvalds" },
    { title: "Radical Candor", recommender: "amir-salihefendic" },
    { title: "Sapiens", recommender: "amir-salihefendic" },
    { title: "Good to Great", recommender: "amir-salihefendic" },
    { title: "Hooked", recommender: "amir-salihefendic" },
    { title: "Tools Of Titans", recommender: "amir-salihefendic" },
    { title: "Siddhartha", recommender: "amir-salihefendic" },
    { title: "The Courage to Be Disliked", recommender: "amir-salihefendic" },
    { title: "Homo Deus", recommender: "amir-salihefendic" },
    { title: "Competing Against Luck", recommender: "amir-salihefendic" },
    { title: "The Score Takes Care of Itself", recommender: "amir-salihefendic" },
    { title: "Reboot", recommender: "amir-salihefendic" },
    { title: "Crossing the Chasm", recommender: "amir-salihefendic" },
    { title: "Rework", recommender: "amir-salihefendic" },
    { title: "Let My People Go Surfing", recommender: "amir-salihefendic" },
    { title: "Only the Paranoid Survive", recommender: "amir-salihefendic" },
    { title: "Positioning", recommender: "amir-salihefendic" },
    { title: "The Inner Game Of Tennis", recommender: "amir-salihefendic" },
    { title: "The Minimalist Entrepreneur", recommender: "john-green" },
    { title: "Zero to One", recommender: "nassim-nicholas-taleb" },
    { title: "Seeking Wisdom", recommender: "nassim-nicholas-taleb" },
    { title: "Predictably Irrational, Revised and Expanded Edition", recommender: "nassim-nicholas-taleb" },
    { title: "Mathematics", recommender: "nassim-nicholas-taleb" },
    { title: "Good Calories, Bad Calories", recommender: "nassim-nicholas-taleb" },
    { title: "Montaigne", recommender: "nassim-nicholas-taleb" },
    { title: "Bull!", recommender: "nassim-nicholas-taleb" },
    { title: "The Paradox of Choice", recommender: "nassim-nicholas-taleb" },
    { title: "The Intelligent Investor Rev Ed. The Definitive Book on Value Investing", recommender: "jamie-dimon" },
    { title: "How to Invest", recommender: "jamie-dimon" },
    { title: "Connecting the Dots", recommender: "jamie-dimon" },
    { title: "Guns, Germs, and Steel", recommender: "jamie-dimon" },
    { title: "Security Analysis, Sixth Edition", recommender: "jamie-dimon" },
    { title: "Sam Walton", recommender: "jamie-dimon" },
    { title: "Winning", recommender: "jamie-dimon" },
    { title: "Only the Paranoid Survive", recommender: "jamie-dimon" },
    { title: "Life Is What You Make It", recommender: "jamie-dimon" },
    { title: "Snow Crash", recommender: "bret-victor" },
    { title: "The Inmates Are Running the Asylum", recommender: "bret-victor" },
    { title: "Structure and Interpretation of Computer Programs", recommender: "bret-victor" },
    { title: "About Face", recommender: "bret-victor" },
    { title: "Envisioning Information", recommender: "bret-victor" },
    { title: "Understanding Comics", recommender: "bret-victor" },
    { title: "The Origin of Consciousness in the Breakdown of the Bicameral Mind", recommender: "bret-victor" },
    { title: "The Visual Display of Quantitative Information", recommender: "bret-victor" },
    { title: "Visual Explanations", recommender: "bret-victor" },
    { title: "Mathematics", recommender: "bret-victor" },
    { title: "The Minimalist Entrepreneur", recommender: "derek-sivers" },
    { title: "The Art of SEO", recommender: "derek-sivers" },
    { title: "Just Mercy", recommender: "chris-sacca" },
    { title: "What Really Makes America Great", recommender: "chris-sacca" }];